name: "Check Conventional Latest Commit"
description: "Checks if the latest commit follows the Conventional Commits specification."
author: "mail@fabriziocacicia.com"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "mic"
  color: "black"
