name: "Check Latest Commit Conventional"
description: "Checks if the latest commit follows the Conventional Commits convention."
author: "mail@fabriziocacicia.com"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "mic"
  color: "black"
